version: "3.2"


services:
  ghasreview:
    build: .
    #image: ghcr.io/geekmasher/ghas-reviewer-app:main
    container_name: ghasreview
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./config:/ghasreview/config
    security_opt:
      - no-new-privileges:true

